### ISSUE TITLE
Use Vagrant::Action::Builtin::GracefulHalt

### ISSUE THREAD

**Issue by sciurus** [pradels/vagrant-libvirt#191] opened 2014-05-25 20:00 UTC
Use the builtin [GracefulHalt](https://github.com/mitchellh/vagrant/blob/v1.5.4/lib/vagrant/action/builtin/graceful_halt.rb) instead of VagrantPlugins::ProviderLibvirt::Action::HaltDomain. Sample usage [here](https://github.com/mitchellh/vagrant/blob/master/plugins/providers/virtualbox/action.rb#L123). We'll still need our own action action to run if graceful halt fails.

**Comment by infernix** [comment] 2016-04-08 11:56
I will close this as a dupe of #10 since graceful shutdown will need to be improved alltogether; this can be included in that process.

**Closed by infernix** 2016-04-08 11:56 UTC
