### ISSUE TITLE
Tunnel source IP not configurable via libvirt__tunnel_ip

### ISSUE THREAD

**Issue by muelli** [pradels/vagrant-libvirt#492] opened 2015-10-26 09:24 UTC
I have two physical hosts and I want virtual machines running on them to talk to each via a private network.  I thought libvirt's tunnelling mechanism is appropriate.

Now I've tried to follow the examples in the readme to bind the TCP server port on 0.0.0.0, but I failed.
I ended up trying this:

```
  config.vm.define "trusty" do |machine|
    machine.vm.network "private_network",
        :libvirt__tunnel_type => 'server',
        :libvirt__tunnel_ip => '0.0.0.0',
        :libvirt__tcp_tunnel_ip => '0.0.0.0',
        :libvirt__tunnel_local_ip => '0.0.0.0',
        :libvirt__tcp_tunnel_local_ip => '0.0.0.0',
        :libvirt__tunnel_port => 33344,
        :libvirt__tunnel_local_port => 33345
  end
```
which yields this machine XML:

```
    <interface type='server'>
      <mac address='52:54:00:48:a4:76'/>
      <source address='127.0.0.1' port='33344'/>
      <model type='virtio'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </interface>
```
I am missing the "0.0.0.0" in the `<source address=>`.

Similarly, I'm trying to make a client connect to the remote host, but I seem to be unable to configure the target IP address.
I've ended up trying
```

    config.vm.network "private_network",
        :libvirt__tunnel_type => 'client',
        :libvirt__tunnel_ip => '10.200.17.123',
        :libvirt__tcp_tunnel_ip => '10.200.17.123',
        :libvirt__tunnel_port => 33344

```
which yields
```
    <interface type='client'>
      <mac address='52:54:00:85:5d:f7'/>
      <source address='127.0.0.1' port='33344'/>
      <model type='virtio'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
```
and again, the target IP address is missing in the XML description.

I seem to be running libvirt0-1.2.16-2ubuntu9 with vagrant-libvirt (0.0.32).

**Comment by skamithi** [comment] 2016-03-23 14:19
I will see if this bug is still valid. I am the original submitter of this feature.

**Comment by infernix** [comment] 2016-03-29 20:58
@muelli a few pointers:

- There are no `libvirt__tcp_tunnel_*` flags.
- For TCP server tunnels, `libvirt__tunnel_ip`is the valid flag to use for the `source address` field
- It appears there documentation is wrong, because the flag referenced in the source is `libvirt__tunnel_address` while the documentation says `libvirt__tunnel_ip`

@skamithi if you could take a look at this and submit a PR that'd be great; I just ran into this as well while playing with CumulusVX.

**Comment by skamithi** [comment] 2016-03-29 21:23
I'll get it fixed  in a few days. thx.

**Comment by skamithi** [comment] 2016-03-31 15:34
There is still a problem with doing the same for UDP Tunnels. Looks like a libvirt/qemu issue. I will investigate and resolve because I have a need for this feature.

```
Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: bind: Cannot assign requested address
2016-03-31T15:20:53.276785Z qemu-system-x86_64: -netdev socket,udp=192.168.96.111:3000,localaddr=192.168.96.112:4000,id=hostnet1: Device 'socket' could not be initialized
```

**Comment by infernix** [comment] 2016-03-31 16:51
Let's keep this open until we have some feedback on the UDP issue.

**Comment by infernix** [comment] 2016-03-31 16:57
@skamithi FWIW I had no problems with this config:

```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "CumulusVX-2.5.6-4048c0a8213324c0-libvirt"
  config.vm.box = "https://spirit.infernix.net/vagrant/CumulusVX-2.5.6-4048c0a8213324c0-libvirt.box"
  config.vm.network :private_network, 
    :libvirt__tunnel_type => 'udp', 
    :libvirt__tunnel_local_ip => '192.168.0.3',
    :libvirt__tunnel_local_port => 30001,
    :libvirt__tunnel_ip => '192.168.0.3',
    :libvirt__tunnel_port => 31001

  config.vm.provider "libvirt" do |vb|
    vb.memory = 4000
    vb.cpus = 2
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
```

Results in this domain XML snippet:
```xml
    <interface type='udp'>
      <mac address='52:54:00:44:b9:1a'/>
      <source address='192.168.0.3' port='31001'>
        <local address='192.168.0.3' port='30001'/>
      </source>
      <target dev='tnet1'/>
      <model type='virtio'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>
```

And this commandline snippet:

`-netdev socket,udp=192.168.0.3:31001,localaddr=192.168.0.3:30001,id=hostnet1 `

Can you confirm the issue is local? I'm on libvirt 1.3.1 with qemu 2.5.

**Comment by skamithi** [comment] 2016-03-31 20:12
I'm on an older libvirt and QEMU. I will upgrade and confirm it works. Thanks for the info.

**Comment by skamithi** [comment] 2016-04-01 04:26
the problem is with the addressing. If you specify a ``libvirt_tunnel_local_ip`` address that is not assigned to the host you get the error I saw. So you are right, the issue is  just me typing in the wrong IP. in future vagrant files I create,  I'll write some ruby so it parses the interface data and picks the correct IP.  Not a libvirt/qemu issue. Just user error :)

**Comment by infernix** [comment] 2016-04-01 10:29
Thanks for confirming :+1:

**Closed by infernix** 2016-04-01 10:29 UTC
Labels: bug
