### ISSUE TITLE
Remove or Replace base box image in storage pool.

### ISSUE THREAD

**Issue by pradels** [pradels/vagrant-libvirt#14] opened 2013-04-10 11:30 UTC
There is no option to remove or replace image placed as volume in libvirt storage pool. It can be only uploaded in current version.
Also if uploading was interrupted, image need to be removed manually.

**Comment by infernix** [comment] 2016-03-28 15:38
I suppose the issue here is primarily the fact that if a vagrant box is removed, the image in the storage pool is not deleted; the same likely goes for replacing a vagrant box with a newer version or even upgrading box versions.

This needs some testing to better define the problem before the feature can be added; in all likelihood this means full support for vagrant box versions.

**Comment by infernix** [comment] 2016-03-29 12:21
Closing this as duplicate of #85 where there's a much better discussion around this issue.

**Closed by infernix** 2016-03-29 12:21 UTC
Labels: duplicate
