### ISSUE TITLE
<VagrantPlugins::ProviderLibvirt::Action::CreateDomain:0x00000101565bb0> (NameError)

### ISSUE THREAD

**Issue by jcalonsoh** [pradels/vagrant-libvirt#201] opened 2014-06-17 23:38 UTC
hi i am having problems with this error 

```
Vagrant.require_plugin is deprecated and has no effect any longer.
Use `vagrant plugin` commands to manage plugins. This warning will
be removed in the next version of Vagrant.
Bringing machine 'vm1' up with 'libvirt' provider...
==> vm1: Creating image (snapshot of base box volume).
==> vm1: Creating domain with the following settings...
==> vm1:  -- Name:          ansible-universe_vm1
==> vm1:  -- Domain type:   xen
==> vm1:  -- Cpus:          2
==> vm1:  -- Memory:        2048M
==> vm1:  -- Base box:      baremettle/centos-6.5
==> vm1:  -- Storage pool:  default
==> vm1:  -- Image:         /var/lib/libvirt/images/ansible-universe_vm1.img
==> vm1:  -- Volume Cache:  writethrough
==> vm1:  -- Kernel:        
==> vm1:  -- Initrd:        
==> vm1:  -- Disks:         vdb(qcow2,10G), vdc(qcow2,50G)
==> vm1:  -- Disk(vdb):     /var/lib/libvirt/images/ansible-universe_vm1-vdb.qcow2
==> vm1:  -- Disk(vdc):     /var/lib/libvirt/images/ansible-universe_vm1-vdc.qcow2
==> vm1:  -- Command line : 
(erubis:29:in `to_xml': undefined local variable or method `d' for #<VagrantPlugins::ProviderLibvirt::Action::CreateDomain:0x00000101565bb0> (NameError)
	from /Applications/Vagrant/embedded/gems/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /Applications/Vagrant/embedded/gems/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /Users/jcalonsoh/.vagrant.d/gems/gems/vagrant-libvirt-0.0.16/lib/vagrant-libvirt/util/erb_template.rb:18:in `to_xml'
	from /Users/jcalonsoh/.vagrant.d/gems/gems/vagrant-libvirt-0.0.16/lib/vagrant-libvirt/action/create_domain.rb:105:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jcalonsoh/.vagrant.d/gems/gems/vagrant-libvirt-0.0.16/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jcalonsoh/.vagrant.d/gems/gems/vagrant-libvirt-0.0.16/lib/vagrant-libvirt/action/handle_box_image.rb:38:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jcalonsoh/.vagrant.d/gems/gems/vagrant-libvirt-0.0.16/lib/vagrant-libvirt/action/handle_storage_pool.rb:21:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jcalonsoh/.vagrant.d/gems/gems/vagrant-libvirt-0.0.16/lib/vagrant-libvirt/action/set_name_of_domain.rb:42:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jcalonsoh/.vagrant.d/gems/gems/vagrant-libvirt-0.0.16/lib/vagrant-libvirt/action/connect_libvirt.rb:88:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:434:in `lock'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

please help

**Comment by infernix** [comment] 2016-04-08 12:29
I've tried to reproduce this under vagrant 1.8.1 with vagrant-libvirt 0.3.3 using kvm and could not reproduce the error.

Since this is an old bug with no comments for almost 2 years, I'm closing this; if it continues to be an issue, please feel free to reopen it. Thanks.

**Closed by infernix** 2016-04-08 12:29 UTC
