### ISSUE TITLE
config.vm.boot_timeout not supported

### ISSUE THREAD

**Issue by brecode** [pradels/vagrant-libvirt#288] opened 2014-12-22 21:14 UTC
Hello, 

Is there a way to set a time_out for this plugin ?
In vagrant there is config.vm.boot_timeout which can be set in seconds. 
Do you have a similar command or maybe know why the above won't work ?

**Comment by infernix** [comment] 2016-04-25 15:18
Closing as duplicate of #193

**Closed by infernix** 2016-04-25 15:18 UTC
