### ISSUE TITLE
Can't discover guest if eth0 is static

### ISSUE THREAD

**Issue by rbellamy** [pradels/vagrant-libvirt#359] opened 2015-05-05 02:44 UTC
I've got an box that (for various reasons) has a static IP (`192.168.42.15`) on eth0.

When I `vagrant up` with default settings (`management_network_address = '192.168.121.0/24'`), vagrant sits there and waits for the IP address.

```
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::StartDomain:0x0000000288f638>
 INFO interface: info: Starting domain.
 INFO interface: info: ==> default: Starting domain.
==> default: Starting domain.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x000000028eb578>
 INFO interface: info: Waiting for domain to get an IP address...
 INFO interface: info: ==> default: Waiting for domain to get an IP address...
==> default: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```

Next I try to set the management network address explicitly:
```ruby
config.vm.provider :libvirt do |libvirt|
    # configure libvirt
    libvirt.management_network_address = '192.168.42.0/24'    
end
```

This works, but only after I use virt-viewer and ping from within the guest as seen in [this screencast](https://drive.google.com/file/d/0B6tWvzmRA3oQeXNMY2dPTTFQb2c/view).

When viewing the arp table at `/proc/net/arp` the expected IP address doesn't show until the ping from the guest is initiated.

*Before guest ping:*
```
2015-05-04 19:25:25
root@eanna i /etc/systemd/system # grep "192.168.42" /proc/net/arp
zsh: exit 1     grep --color=auto "192.168.42" /proc/net/arp
```
*After guest ping:*
```
2015-05-04 19:25:38
root@eanna i /etc/systemd/system # grep "192.168.42" /proc/net/arp
192.168.42.15    0x1         0x2         52:54:00:ea:1e:11     *        virbr1
```

Which leads me to believe that the `arp` method of determining the guests IPs isn't working for me.

Furthermore, there is nothing in `/var/lib/libvirt/dnsmasq/` that has the management IP address, so the old way of looking in a `*.leases` file won't work either.

My question is - what's the guidance on static IPs in the guest?

**Comment by rbellamy** [comment] 2015-05-08 23:44
And I've just confirmed that the host pinging the guest will also fill the arp cache.

**Comment by purpleidea** [comment] 2015-05-21 21:56
Not sure if this is related to https://bugzilla.redhat.com/show_bug.cgi?id=1221006

**Comment by infernix** [comment] 2016-04-25 16:21
I'm afraid this is more or less by design.

It's certainly not ideal to do guest ip detection by looking at arp cache, but we simply expect the VM to send dhcp requests on the vagrant-managed interface. If you really need a static address for a VM, use the private interfaces definitions in your Vagrantfile and Vagrant will set that all up for you. As far as I know this works the same for all providers in Vagrant.

So I'm closing this as I don't see why you couldn't use a private network definition for your static IP - that's what it's there for. If you have really strong arguments for not being able to use it then please comment.

**Closed by infernix** 2016-04-25 16:21 UTC
