### ISSUE TITLE
ruby-libvirt doesn't install on ubuntu 15.04

### ISSUE THREAD

**Issue by alexanderkjeldaas** [pradels/vagrant-libvirt#403] opened 2015-06-24 08:01 UTC
I get the following error when installing the vagrant-libvirt plugin on ubuntu 15.04 vivid:

$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ruby-libvirt (0.5.2), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.5.2'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

Gem files will remain installed in /root/.vagrant.d/gems/gems/ruby-libvirt-0.5.2 for inspection.
Results logged to /root/.vagrant.d/gems/gems/ruby-libvirt-0.5.2/ext/libvirt/gem_make.out

**Comment by jlferrer** [comment] 2015-06-28 20:28
Hi,

Perhaps the cause is that the build process does not found libvirt header files, try to install indicating this build options:

```
CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib" vagrant plugin install vagrant-libvirt
```

**Comment by alq666** [comment] 2015-09-01 18:50
This is indeed the reason (verified on 15.04). Getting other errors past that one, but that's clearly a step in the right direction.

**Comment by electrofelix** [comment] 2015-09-15 15:21
Encountered this recently and discovered that the reason the build fails to find the header files is due to `pkg-config` being missing from the system. Simply installing this package solved the problem.

**Comment by dragoscirjan** [comment] 2015-10-13 21:55
Hi, I'm experiencing a similar issue. When trying to run 
```bash
vagrant plugin install vagrant-libvirt
```
I get the following error: http://pastebin.com/fLx6Uzhq

However, if I try to install the gem alone, everything goes well.
```bash
root@a1mldragosc-y5070:~# gem install ruby-libvirt -v '0.5.2'
Building native extensions.  This could take a while...
Successfully installed ruby-libvirt-0.5.2
Parsing documentation for ruby-libvirt-0.5.2
Done installing documentation for ruby-libvirt after 0 seconds
1 gem installed
```

It may be a different bug, and I think I'm missing a library, but... don't get which one.

**Comment by electrofelix** [comment] 2015-10-15 13:53
@dragoscirjan Your example of installing the gem alone is installing to your system ruby, instead of the vagrant ruby environment. Maybe try `vagrant plugin install --plugin-version 0.5.2 ruby-libvirt` and see if there is an error thrown by vagrant just for the install of that gem.

**Comment by chaim1221** [comment] 2016-01-26 16:05
This may be unrelated, but...

`$ dpkg -P chefdk`

`$ aptitude purge ruby`

`$ sudo apt-get remove vagrant`

`$ sudo apt-get remove libvirt-dev`

`$ sudo apt-get autoremove`

`$ sudo apt-get install libvirt-dev`

`# because sudo apt-get install gets 1.7.4, I got latest from vagrant:`
`$ sudo dpkg -i /Downloads/vagrant_1.8.1_x86_64.deb`

and FINALLY...
```
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Installed the plugin 'vagrant-libvirt (0.0.32)'!
```

**Comment by alq666** [comment] 2016-01-26 16:12
@chaim1221 confirmed, same results here.

**Comment by infernix** [comment] 2016-04-25 17:55
I'm closing this as this is now outdated (newer ruby-libvirt is out) and it's not a vagrant-libvirt issue plus there's other issues related to this already. I'm planning to address the many build issues everyone reported with #590 in the not too distant future.

**Closed by infernix** 2016-04-25 17:55 UTC

**Comment by chaim1221** [comment] 2016-04-25 22:32
I can confirm it's not (and wasn't) a vagrant-libvirt issue, at least not on my end. It's more an issue with the Ubuntu package manager. If you go to their website, Vagrant tells you to install latest from them (not from package sources). See steps above.
